/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CertificateArn": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DailyDash": {
      "type": "sst.aws.Nextjs"
    }
    "Domain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FromEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleAuthId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}