/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AuthDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DailyDash": {
      "type": "sst.aws.Nextjs"
    }
    "Domain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OllyAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}