import {
  Sun,
  CloudSun,
  Cloud,
  CloudFog,
  Droplets,
  CloudRain,
  CloudSnow,
  Snowflake,
  CloudDrizzle,
  CloudLightning,
  CloudHail,
  Moon,
  MoonStar,
  CloudMoon
} from "lucide-react";
import { WeatherTheme } from "@/lib/weather/utils/types"
  
export const WEATHER_CODE_MAP: Record<number, { theme: WeatherTheme; description: string }> = {
  0: { theme: "sunny", description: "Clear sky" },
  1: { theme: "partly-cloudy", description: "Mainly clear" },
  2: { theme: "partly-cloudy", description: "Partly cloudy" },
  3: { theme: "cloudy", description: "Overcast" },
  45: { theme: "cloudy", description: "Foggy" },
  48: { theme: "cloudy", description: "Depositing rime fog" },
  51: { theme: "light-rain", description: "Light drizzle" },
  53: { theme: "light-rain", description: "Moderate drizzle" },
  55: { theme: "light-rain", description: "Dense drizzle" },
  61: { theme: "rain", description: "Light rain" },
  63: { theme: "rain", description: "Moderate rain" },
  65: { theme: "rain", description: "Heavy rain" },
  66: { theme: "snow", description: "Freezing rain" },
  67: { theme: "snow", description: "Heavy freezing rain" },
  71: { theme: "snow", description: "Slight snow" },
  73: { theme: "snow", description: "Moderate snow" },
  75: { theme: "snow", description: "Heavy snow" },
  77: { theme: "snow", description: "Snow grains" },
  80: { theme: "light-rain", description: "Slight rain showers" },
  81: { theme: "rain", description: "Moderate rain showers" },
  82: { theme: "rain", description: "Violent rain showers" },
  95: { theme: "thunderstorm", description: "Thunderstorm" },
  96: { theme: "thunderstorm", description: "Thunderstorm with hail" },
  99: { theme: "thunderstorm", description: "Severe thunderstorm" },
};

export const WEATHER_ICON_MAP: Record<number, typeof Sun> = {
  0: Sun,
  1: CloudSun,
  2: CloudSun,
  3: Cloud,
  45: CloudFog,
  48: CloudFog,
  51: CloudDrizzle,
  53: CloudDrizzle,
  55: CloudDrizzle,
  61: CloudRain,
  63: CloudRain,
  65: CloudRain,
  66: CloudSnow,
  67: CloudSnow,
  71: Snowflake,
  73: Snowflake,
  75: CloudSnow,
  77: CloudSnow,
  80: Droplets,
  81: CloudRain,
  82: CloudRain,
  95: CloudLightning,
  96: CloudHail,
  99: CloudLightning,
};
export const NIGHT_WEATHER_ICON_MAP: Record<number, typeof Sun> = {
  0: MoonStar,
  1: CloudMoon,
  2: CloudMoon,
  3: Cloud,
  45: CloudFog,
  48: CloudFog,
  51: CloudDrizzle,
  53: CloudDrizzle,
  55: CloudDrizzle,
  61: CloudRain,
  63: CloudRain,
  65: CloudRain,
  66: CloudSnow,
  67: CloudSnow,
  71: Snowflake,
  73: Snowflake,
  75: CloudSnow,
  77: CloudSnow,
  80: Droplets,
  81: CloudRain,
  82: CloudRain,
  95: CloudLightning,
  96: CloudHail,
  99: CloudLightning,
};
