export const BASE_FEED_URL = "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs";
export const LINE_FEED_SUFFIXES: Record<string, string> = {
  L: "-l",
  A: "-ace",
  C: "-ace",
  E: "-ace",
  SR: "-ace",
  G: "-g",
  N: "-nqrw",
  Q: "-nqrw",
  R: "-nqrw",
  W: "-nqrw",
  S: "",
  "1": "",
  "2": "",
  "3": "",
  "4": "",
  "5": "",
  "6": "",
  "7": "",
  B: "-bdfm",
  D: "-bdfm",
  F: "-bdfm",
  M: "-bdfm",
  J: "-jz",
  Z: "-jz",
  SIR: "-si",
};

const red123 = "#EE352E"
const blue456 = "#00933C"
const purple_7 = "#B933AD"
const lgrey = "#A7A9AC"
const s_grey = "#808183"
const nqrwyellow = "#FCCC0A"
const ace_blue = "#0039A6"
const bdfm_orange = "#FF6319"
const g_green = "#6CBE45"
const jz_brown = "#996633"

export const SUBWAY_COLORS = {
  "1": red123,
  "2": red123,
  "3": red123,
  "4": blue456,
  "5": blue456,
  "6": blue456,
  "6X": blue456,
  "7": purple_7,
  "7X": purple_7,
  "L": lgrey,
  "N": nqrwyellow,
  "Q": nqrwyellow,
  "R": nqrwyellow,
  "W": nqrwyellow,
  "A": ace_blue,
  "C": ace_blue,
  "E": ace_blue,
  "B": bdfm_orange,
  "D": bdfm_orange,
  "F": bdfm_orange,
  "M": bdfm_orange,
  "G": g_green,
  "J": jz_brown,
  "Z": jz_brown
};

export const STOPS_BY_LINE = {
    "1": [
      { id: "119", name: "103 St" },
      { id: "117", name: "116 St-Columbia University" },
      { id: "116", name: "125 St" },
      { id: "115", name: "137 St-City College" },
      { id: "132", name: "14 St" },
      { id: "114", name: "145 St" },
      { id: "113", name: "157 St" },
      { id: "112", name: "168 St-Washington Hts" },
      { id: "131", name: "18 St" },
      { id: "111", name: "181 St" },
      { id: "110", name: "191 St" },
      { id: "108", name: "207 St" },
      { id: "107", name: "215 St" },
      { id: "130", name: "23 St" },
      { id: "104", name: "231 St" },
      { id: "103", name: "238 St" },
      { id: "129", name: "28 St" },
      { id: "128", name: "34 St-Penn Station" },
      { id: "126", name: "50 St" },
      { id: "125", name: "59 St-Columbus Circle" },
      { id: "124", name: "66 St-Lincoln Center" },
      { id: "123", name: "72 St" },
      { id: "122", name: "79 St" },
      { id: "121", name: "86 St" },
      { id: "120", name: "96 St" },
      { id: "135", name: "Canal St" },
      { id: "118", name: "Cathedral Pkwy (110 St)" },
      { id: "137", name: "Chambers St" },
      { id: "133", name: "Christopher St-Stonewall" },
      { id: "109", name: "Dyckman St" },
      { id: "136", name: "Franklin St" },
      { id: "134", name: "Houston St" },
      { id: "106", name: "Marble Hill-225 St" },
      { id: "139", name: "Rector St" },
      { id: "142", name: "South Ferry" },
      { id: "127", name: "Times Sq-42 St" },
      { id: "101", name: "Van Cortlandt Park-242 St" },
      { id: "138", name: "WTC Cortlandt" },
    ],
    "2": [
      { id: "226", name: "116 St" },
      { id: "225", name: "125 St" },
      { id: "224", name: "135 St" },
      { id: "132", name: "14 St" },
      { id: "222", name: "149 St-Grand Concourse" },
      { id: "215", name: "174 St" },
      { id: "131", name: "18 St" },
      { id: "207", name: "219 St" },
      { id: "206", name: "225 St" },
      { id: "130", name: "23 St" },
      { id: "205", name: "233 St" },
      { id: "129", name: "28 St" },
      { id: "221", name: "3 Av-149 St" },
      { id: "128", name: "34 St-Penn Station" },
      { id: "126", name: "50 St" },
      { id: "125", name: "59 St-Columbus Circle" },
      { id: "124", name: "66 St-Lincoln Center" },
      { id: "123", name: "72 St" },
      { id: "122", name: "79 St" },
      { id: "121", name: "86 St" },
      { id: "120", name: "96 St" },
      { id: "210", name: "Allerton Av" },
      { id: "235", name: "Atlantic Av-Barclays Ctr" },
      { id: "236", name: "Bergen St" },
      { id: "245", name: "Beverly Rd" },
      { id: "232", name: "Borough Hall" },
      { id: "212", name: "Bronx Park East" },
      { id: "209", name: "Burke Av" },
      { id: "135", name: "Canal St" },
      { id: "227", name: "Central Park North (110 St)" },
      { id: "137", name: "Chambers St" },
      { id: "133", name: "Christopher St-Stonewall" },
      { id: "244", name: "Church Av" },
      { id: "231", name: "Clark St" },
      { id: "250", name: "Crown Hts-Utica Av" },
      { id: "213", name: "E 180 St" },
      { id: "238", name: "Eastern Pkwy-Brooklyn Museum" },
      { id: "247", name: "Flatbush Av-Brooklyn College" },
      { id: "239", name: "Franklin Av-Medgar Evers College" },
      { id: "136", name: "Franklin St" },
      { id: "216", name: "Freeman St" },
      { id: "229", name: "Fulton St" },
      { id: "237", name: "Grand Army Plaza" },
      { id: "208", name: "Gun Hill Rd" },
      { id: "134", name: "Houston St" },
      { id: "233", name: "Hoyt St" },
      { id: "218", name: "Intervale Av" },
      { id: "220", name: "Jackson Av" },
      { id: "254", name: "Junius St" },
      { id: "249", name: "Kingston Av" },
      { id: "204", name: "Nereid Av" },
      { id: "234", name: "Nevins St" },
      { id: "257", name: "New Lots Av" },
      { id: "246", name: "Newkirk Av-Little Haiti" },
      { id: "248", name: "Nostrand Av" },
      { id: "228", name: "Park Place" },
      { id: "211", name: "Pelham Pkwy" },
      { id: "255", name: "Pennsylvania Av" },
      { id: "241", name: "President St-Medgar Evers College" },
      { id: "219", name: "Prospect Av" },
      { id: "253", name: "Rockaway Av" },
      { id: "252", name: "Saratoga Av" },
      { id: "217", name: "Simpson St" },
      { id: "242", name: "Sterling St" },
      { id: "251", name: "Sutter Av-Rutland Rd" },
      { id: "127", name: "Times Sq-42 St" },
      { id: "256", name: "Van Siclen Av" },
      { id: "201", name: "Wakefield-241 St" },
      { id: "230", name: "Wall St" },
      { id: "214", name: "West Farms Sq-E Tremont Av" },
      { id: "243", name: "Winthrop St" },
    ],
    "3": [
      { id: "226", name: "116 St" },
      { id: "225", name: "125 St" },
      { id: "224", name: "135 St" },
      { id: "132", name: "14 St" },
      { id: "302", name: "145 St" },
      { id: "128", name: "34 St-Penn Station" },
      { id: "123", name: "72 St" },
      { id: "120", name: "96 St" },
      { id: "235", name: "Atlantic Av-Barclays Ctr" },
      { id: "236", name: "Bergen St" },
      { id: "232", name: "Borough Hall" },
      { id: "227", name: "Central Park North (110 St)" },
      { id: "137", name: "Chambers St" },
      { id: "231", name: "Clark St" },
      { id: "250", name: "Crown Hts-Utica Av" },
      { id: "238", name: "Eastern Pkwy-Brooklyn Museum" },
      { id: "239", name: "Franklin Av-Medgar Evers College" },
      { id: "229", name: "Fulton St" },
      { id: "237", name: "Grand Army Plaza" },
      { id: "301", name: "Harlem-148 St" },
      { id: "233", name: "Hoyt St" },
      { id: "254", name: "Junius St" },
      { id: "249", name: "Kingston Av" },
      { id: "234", name: "Nevins St" },
      { id: "257", name: "New Lots Av" },
      { id: "248", name: "Nostrand Av" },
      { id: "228", name: "Park Place" },
      { id: "255", name: "Pennsylvania Av" },
      { id: "253", name: "Rockaway Av" },
      { id: "252", name: "Saratoga Av" },
      { id: "251", name: "Sutter Av-Rutland Rd" },
      { id: "127", name: "Times Sq-42 St" },
      { id: "256", name: "Van Siclen Av" },
      { id: "230", name: "Wall St" },
    ],
    "4": [
      { id: "624", name: "103 St" },
      { id: "623", name: "110 St" },
      { id: "622", name: "116 St" },
      { id: "621", name: "125 St" },
      { id: "416", name: "138 St-Grand Concourse" },
      { id: "635", name: "14 St-Union Sq" },
      { id: "415", name: "149 St-Grand Concourse" },
      { id: "414", name: "161 St-Yankee Stadium" },
      { id: "413", name: "167 St" },
      { id: "412", name: "170 St" },
      { id: "410", name: "176 St" },
      { id: "408", name: "183 St" },
      { id: "634", name: "23 St" },
      { id: "633", name: "28 St" },
      { id: "632", name: "33 St" },
      { id: "630", name: "51 St" },
      { id: "629", name: "59 St" },
      { id: "628", name: "68 St-Hunter College" },
      { id: "627", name: "77 St" },
      { id: "626", name: "86 St" },
      { id: "625", name: "96 St" },
      { id: "636", name: "Astor Pl" },
      { id: "235", name: "Atlantic Av-Barclays Ctr" },
      { id: "405", name: "Bedford Park Blvd-Lehman College" },
      { id: "236", name: "Bergen St" },
      { id: "637", name: "Bleecker St" },
      { id: "423", name: "Borough Hall" },
      { id: "420", name: "Bowling Green" },
      { id: "640", name: "Brooklyn Bridge-City Hall" },
      { id: "409", name: "Burnside Av" },
      { id: "639", name: "Canal St" },
      { id: "250", name: "Crown Hts-Utica Av" },
      { id: "238", name: "Eastern Pkwy-Brooklyn Museum" },
      { id: "407", name: "Fordham Rd" },
      { id: "239", name: "Franklin Av-Medgar Evers College" },
      { id: "418", name: "Fulton St" },
      { id: "237", name: "Grand Army Plaza" },
      { id: "631", name: "Grand Central-42 St" },
      { id: "254", name: "Junius St" },
      { id: "406", name: "Kingsbridge Rd" },
      { id: "249", name: "Kingston Av" },
      { id: "402", name: "Mosholu Pkwy" },
      { id: "411", name: "Mt Eden Av" },
      { id: "234", name: "Nevins St" },
      { id: "257", name: "New Lots Av" },
      { id: "248", name: "Nostrand Av" },
      { id: "255", name: "Pennsylvania Av" },
      { id: "253", name: "Rockaway Av" },
      { id: "252", name: "Saratoga Av" },
      { id: "638", name: "Spring St" },
      { id: "251", name: "Sutter Av-Rutland Rd" },
      { id: "256", name: "Van Siclen Av" },
      { id: "419", name: "Wall St" },
      { id: "401", name: "Woodlawn" },
    ],
    "5": [
      { id: "621", name: "125 St" },
      { id: "416", name: "138 St-Grand Concourse" },
      { id: "635", name: "14 St-Union Sq" },
      { id: "222", name: "149 St-Grand Concourse" },
      { id: "215", name: "174 St" },
      { id: "207", name: "219 St" },
      { id: "206", name: "225 St" },
      { id: "205", name: "233 St" },
      { id: "221", name: "3 Av-149 St" },
      { id: "629", name: "59 St" },
      { id: "626", name: "86 St" },
      { id: "210", name: "Allerton Av" },
      { id: "235", name: "Atlantic Av-Barclays Ctr" },
      { id: "502", name: "Baychester Av" },
      { id: "245", name: "Beverly Rd" },
      { id: "423", name: "Borough Hall" },
      { id: "420", name: "Bowling Green" },
      { id: "212", name: "Bronx Park East" },
      { id: "640", name: "Brooklyn Bridge-City Hall" },
      { id: "209", name: "Burke Av" },
      { id: "244", name: "Church Av" },
      { id: "250", name: "Crown Hts-Utica Av" },
      { id: "213", name: "E 180 St" },
      { id: "501", name: "Eastchester-Dyre Av" },
      { id: "247", name: "Flatbush Av-Brooklyn College" },
      { id: "239", name: "Franklin Av-Medgar Evers College" },
      { id: "216", name: "Freeman St" },
      { id: "418", name: "Fulton St" },
      { id: "631", name: "Grand Central-42 St" },
      { id: "503", name: "Gun Hill Rd" },
      { id: "208", name: "Gun Hill Rd" },
      { id: "218", name: "Intervale Av" },
      { id: "220", name: "Jackson Av" },
      { id: "254", name: "Junius St" },
      { id: "249", name: "Kingston Av" },
      { id: "505", name: "Morris Park" },
      { id: "204", name: "Nereid Av" },
      { id: "234", name: "Nevins St" },
      { id: "257", name: "New Lots Av" },
      { id: "246", name: "Newkirk Av-Little Haiti" },
      { id: "248", name: "Nostrand Av" },
      { id: "504", name: "Pelham Pkwy" },
      { id: "211", name: "Pelham Pkwy" },
      { id: "255", name: "Pennsylvania Av" },
      { id: "241", name: "President St-Medgar Evers College" },
      { id: "219", name: "Prospect Av" },
      { id: "253", name: "Rockaway Av" },
      { id: "252", name: "Saratoga Av" },
      { id: "217", name: "Simpson St" },
      { id: "242", name: "Sterling St" },
      { id: "251", name: "Sutter Av-Rutland Rd" },
      { id: "256", name: "Van Siclen Av" },
      { id: "419", name: "Wall St" },
      { id: "214", name: "West Farms Sq-E Tremont Av" },
      { id: "243", name: "Winthrop St" },
    ],
    "6": [
      { id: "624", name: "103 St" },
      { id: "623", name: "110 St" },
      { id: "622", name: "116 St" },
      { id: "621", name: "125 St" },
      { id: "635", name: "14 St-Union Sq" },
      { id: "634", name: "23 St" },
      { id: "633", name: "28 St" },
      { id: "619", name: "3 Av-138 St" },
      { id: "632", name: "33 St" },
      { id: "630", name: "51 St" },
      { id: "629", name: "59 St" },
      { id: "628", name: "68 St-Hunter College" },
      { id: "627", name: "77 St" },
      { id: "626", name: "86 St" },
      { id: "625", name: "96 St" },
      { id: "636", name: "Astor Pl" },
      { id: "637", name: "Bleecker St" },
      { id: "618", name: "Brook Av" },
      { id: "640", name: "Brooklyn Bridge-City Hall" },
      { id: "602", name: "Buhre Av" },
      { id: "639", name: "Canal St" },
      { id: "607", name: "Castle Hill Av" },
      { id: "617", name: "Cypress Av" },
      { id: "616", name: "E 143 St-St Mary's St" },
      { id: "615", name: "E 149 St" },
      { id: "611", name: "Elder Av" },
      { id: "631", name: "Grand Central-42 St" },
      { id: "613", name: "Hunts Point Av" },
      { id: "614", name: "Longwood Av" },
      { id: "603", name: "Middletown Rd" },
      { id: "610", name: "Morrison Av-Soundview" },
      { id: "608", name: "Parkchester" },
      { id: "601", name: "Pelham Bay Park" },
      { id: "638", name: "Spring St" },
      { id: "609", name: "St Lawrence Av" },
      { id: "604", name: "Westchester Sq-E Tremont Av" },
      { id: "612", name: "Whitlock Av" },
      { id: "606", name: "Zerega Av" },
    ],
    "6X": [
      { id: "624", name: "103 St" },
      { id: "623", name: "110 St" },
      { id: "622", name: "116 St" },
      { id: "621", name: "125 St" },
      { id: "635", name: "14 St-Union Sq" },
      { id: "634", name: "23 St" },
      { id: "633", name: "28 St" },
      { id: "619", name: "3 Av-138 St" },
      { id: "632", name: "33 St" },
      { id: "630", name: "51 St" },
      { id: "629", name: "59 St" },
      { id: "628", name: "68 St-Hunter College" },
      { id: "627", name: "77 St" },
      { id: "626", name: "86 St" },
      { id: "625", name: "96 St" },
      { id: "636", name: "Astor Pl" },
      { id: "637", name: "Bleecker St" },
      { id: "640", name: "Brooklyn Bridge-City Hall" },
      { id: "602", name: "Buhre Av" },
      { id: "639", name: "Canal St" },
      { id: "607", name: "Castle Hill Av" },
      { id: "631", name: "Grand Central-42 St" },
      { id: "613", name: "Hunts Point Av" },
      { id: "603", name: "Middletown Rd" },
      { id: "608", name: "Parkchester" },
      { id: "601", name: "Pelham Bay Park" },
      { id: "638", name: "Spring St" },
      { id: "604", name: "Westchester Sq-E Tremont Av" },
      { id: "606", name: "Zerega Av" },
    ],
    "7": [
      { id: "706", name: "103 St-Corona Plaza" },
      { id: "705", name: "111 St" },
      { id: "716", name: "33 St-Rawson St" },
      { id: "726", name: "34 St-Hudson Yards" },
      { id: "715", name: "40 St-Lowery St" },
      { id: "714", name: "46 St-Bliss St" },
      { id: "724", name: "5 Av" },
      { id: "713", name: "52 St" },
      { id: "712", name: "61 St-Woodside" },
      { id: "711", name: "69 St" },
      { id: "710", name: "74 St-Broadway" },
      { id: "709", name: "82 St-Jackson Hts" },
      { id: "708", name: "90 St-Elmhurst Av" },
      { id: "719", name: "Court Sq" },
      { id: "701", name: "Flushing-Main St" },
      { id: "723", name: "Grand Central-42 St" },
      { id: "720", name: "Hunters Point Av" },
      { id: "707", name: "Junction Blvd" },
      { id: "702", name: "Mets-Willets Point" },
      { id: "718", name: "Queensboro Plaza" },
      { id: "725", name: "Times Sq-42 St" },
      { id: "721", name: "Vernon Blvd-Jackson Av" },
    ],
    "7X": [
      { id: "716", name: "33 St-Rawson St" },
      { id: "726", name: "34 St-Hudson Yards" },
      { id: "715", name: "40 St-Lowery St" },
      { id: "714", name: "46 St-Bliss St" },
      { id: "724", name: "5 Av" },
      { id: "713", name: "52 St" },
      { id: "712", name: "61 St-Woodside" },
      { id: "711", name: "69 St" },
      { id: "710", name: "74 St-Broadway" },
      { id: "719", name: "Court Sq" },
      { id: "701", name: "Flushing-Main St" },
      { id: "723", name: "Grand Central-42 St" },
      { id: "720", name: "Hunters Point Av" },
      { id: "707", name: "Junction Blvd" },
      { id: "702", name: "Mets-Willets Point" },
      { id: "718", name: "Queensboro Plaza" },
      { id: "725", name: "Times Sq-42 St" },
      { id: "721", name: "Vernon Blvd-Jackson Av" },
    ],
    "A": [
      { id: "A18", name: "103 St" },
      { id: "A63", name: "104 St" },
      { id: "A64", name: "111 St" },
      { id: "A16", name: "116 St" },
      { id: "A15", name: "125 St" },
      { id: "A14", name: "135 St" },
      { id: "A31", name: "14 St" },
      { id: "A12", name: "145 St" },
      { id: "A11", name: "155 St" },
      { id: "A10", name: "163 St-Amsterdam Av" },
      { id: "A09", name: "168 St" },
      { id: "A07", name: "175 St" },
      { id: "A06", name: "181 St" },
      { id: "A05", name: "190 St" },
      { id: "A30", name: "23 St" },
      { id: "A28", name: "34 St-Penn Station" },
      { id: "A27", name: "42 St-Port Authority Bus Terminal" },
      { id: "A25", name: "50 St" },
      { id: "A24", name: "59 St-Columbus Circle" },
      { id: "A22", name: "72 St" },
      { id: "A59", name: "80 St" },
      { id: "A21", name: "81 St-Museum of Natural History" },
      { id: "A20", name: "86 St" },
      { id: "A60", name: "88 St" },
      { id: "A19", name: "96 St" },
      { id: "H01", name: "Aqueduct Racetrack" },
      { id: "H02", name: "Aqueduct-N Conduit Av" },
      { id: "H14", name: "Beach 105 St" },
      { id: "H10", name: "Beach 25 St" },
      { id: "H09", name: "Beach 36 St" },
      { id: "H08", name: "Beach 44 St" },
      { id: "H07", name: "Beach 60 St" },
      { id: "H06", name: "Beach 67 St" },
      { id: "H12", name: "Beach 90 St" },
      { id: "H13", name: "Beach 98 St" },
      { id: "H04", name: "Broad Channel" },
      { id: "A51", name: "Broadway Junction" },
      { id: "A34", name: "Canal St" },
      { id: "A17", name: "Cathedral Pkwy (110 St)" },
      { id: "A36", name: "Chambers St" },
      { id: "A44", name: "Clinton-Washington Avs" },
      { id: "A03", name: "Dyckman St" },
      { id: "A55", name: "Euclid Av" },
      { id: "H11", name: "Far Rockaway-Mott Av" },
      { id: "A45", name: "Franklin Av" },
      { id: "A38", name: "Fulton St" },
      { id: "A57", name: "Grant Av" },
      { id: "A40", name: "High St" },
      { id: "H03", name: "Howard Beach-JFK Airport" },
      { id: "A42", name: "Hoyt-Schermerhorn Sts" },
      { id: "A02", name: "Inwood-207 St" },
      { id: "A41", name: "Jay St-MetroTech" },
      { id: "A47", name: "Kingston-Throop Avs" },
      { id: "A43", name: "Lafayette Av" },
      { id: "A52", name: "Liberty Av" },
      { id: "A46", name: "Nostrand Av" },
      { id: "A65", name: "Ozone Park-Lefferts Blvd" },
      { id: "A49", name: "Ralph Av" },
      { id: "A50", name: "Rockaway Av" },
      { id: "A61", name: "Rockaway Blvd" },
      { id: "H15", name: "Rockaway Park-Beach 116 St" },
      { id: "A54", name: "Shepherd Av" },
      { id: "A33", name: "Spring St" },
      { id: "A48", name: "Utica Av" },
      { id: "A53", name: "Van Siclen Av" },
      { id: "A32", name: "W 4 St-Wash Sq" },
    ],
    "B": [
      { id: "A18", name: "103 St" },
      { id: "A16", name: "116 St" },
      { id: "A15", name: "125 St" },
      { id: "A14", name: "135 St" },
      { id: "D13", name: "145 St" },
      { id: "D12", name: "155 St" },
      { id: "D11", name: "161 St-Yankee Stadium" },
      { id: "D10", name: "167 St" },
      { id: "D09", name: "170 St" },
      { id: "D08", name: "174-175 Sts" },
      { id: "D06", name: "182-183 Sts" },
      { id: "D17", name: "34 St-Herald Sq" },
      { id: "D16", name: "42 St-Bryant Pk" },
      { id: "D15", name: "47-50 Sts-Rockefeller Ctr" },
      { id: "A24", name: "59 St-Columbus Circle" },
      { id: "D25", name: "7 Av" },
      { id: "D14", name: "7 Av" },
      { id: "A22", name: "72 St" },
      { id: "A21", name: "81 St-Museum of Natural History" },
      { id: "A20", name: "86 St" },
      { id: "A19", name: "96 St" },
      { id: "D24", name: "Atlantic Av-Barclays Ctr" },
      { id: "D03", name: "Bedford Park Blvd" },
      { id: "D40", name: "Brighton Beach" },
      { id: "D21", name: "Broadway-Lafayette St" },
      { id: "A17", name: "Cathedral Pkwy (110 St)" },
      { id: "D28", name: "Church Av" },
      { id: "R30", name: "DeKalb Av" },
      { id: "D05", name: "Fordham Rd" },
      { id: "D22", name: "Grand St" },
      { id: "D35", name: "Kings Hwy" },
      { id: "D04", name: "Kingsbridge Rd" },
      { id: "D31", name: "Newkirk Plaza" },
      { id: "D26", name: "Prospect Park" },
      { id: "D39", name: "Sheepshead Bay" },
      { id: "D07", name: "Tremont Av" },
      { id: "D20", name: "W 4 St-Wash Sq" },
    ],
    "C": [
      { id: "A18", name: "103 St" },
      { id: "A16", name: "116 St" },
      { id: "A15", name: "125 St" },
      { id: "A14", name: "135 St" },
      { id: "A31", name: "14 St" },
      { id: "A12", name: "145 St" },
      { id: "A11", name: "155 St" },
      { id: "A10", name: "163 St-Amsterdam Av" },
      { id: "A09", name: "168 St" },
      { id: "A30", name: "23 St" },
      { id: "A28", name: "34 St-Penn Station" },
      { id: "A27", name: "42 St-Port Authority Bus Terminal" },
      { id: "A25", name: "50 St" },
      { id: "A24", name: "59 St-Columbus Circle" },
      { id: "A22", name: "72 St" },
      { id: "A21", name: "81 St-Museum of Natural History" },
      { id: "A20", name: "86 St" },
      { id: "A19", name: "96 St" },
      { id: "A51", name: "Broadway Junction" },
      { id: "A34", name: "Canal St" },
      { id: "A17", name: "Cathedral Pkwy (110 St)" },
      { id: "A36", name: "Chambers St" },
      { id: "A44", name: "Clinton-Washington Avs" },
      { id: "A55", name: "Euclid Av" },
      { id: "A45", name: "Franklin Av" },
      { id: "A38", name: "Fulton St" },
      { id: "A40", name: "High St" },
      { id: "A42", name: "Hoyt-Schermerhorn Sts" },
      { id: "A41", name: "Jay St-MetroTech" },
      { id: "A47", name: "Kingston-Throop Avs" },
      { id: "A43", name: "Lafayette Av" },
      { id: "A52", name: "Liberty Av" },
      { id: "A46", name: "Nostrand Av" },
      { id: "A49", name: "Ralph Av" },
      { id: "A50", name: "Rockaway Av" },
      { id: "A54", name: "Shepherd Av" },
      { id: "A33", name: "Spring St" },
      { id: "A48", name: "Utica Av" },
      { id: "A53", name: "Van Siclen Av" },
      { id: "A32", name: "W 4 St-Wash Sq" },
    ],
    "D": [
      { id: "A15", name: "125 St" },
      { id: "D13", name: "145 St" },
      { id: "D12", name: "155 St" },
      { id: "D11", name: "161 St-Yankee Stadium" },
      { id: "D10", name: "167 St" },
      { id: "D09", name: "170 St" },
      { id: "D08", name: "174-175 Sts" },
      { id: "B19", name: "18 Av" },
      { id: "D06", name: "182-183 Sts" },
      { id: "B20", name: "20 Av" },
      { id: "B22", name: "25 Av" },
      { id: "R35", name: "25 St" },
      { id: "D17", name: "34 St-Herald Sq" },
      { id: "R36", name: "36 St" },
      { id: "R33", name: "4 Av-9 St" },
      { id: "D16", name: "42 St-Bryant Pk" },
      { id: "D15", name: "47-50 Sts-Rockefeller Ctr" },
      { id: "B14", name: "50 St" },
      { id: "B15", name: "55 St" },
      { id: "A24", name: "59 St-Columbus Circle" },
      { id: "B16", name: "62 St" },
      { id: "D14", name: "7 Av" },
      { id: "B17", name: "71 St" },
      { id: "B18", name: "79 St" },
      { id: "B12", name: "9 Av" },
      { id: "R31", name: "Atlantic Av-Barclays Ctr" },
      { id: "B23", name: "Bay 50 St" },
      { id: "B21", name: "Bay Pkwy" },
      { id: "D03", name: "Bedford Park Blvd" },
      { id: "D21", name: "Broadway-Lafayette St" },
      { id: "D43", name: "Coney Island-Stillwell Av" },
      { id: "R30", name: "DeKalb Av" },
      { id: "D05", name: "Fordham Rd" },
      { id: "B13", name: "Fort Hamilton Pkwy" },
      { id: "D22", name: "Grand St" },
      { id: "D04", name: "Kingsbridge Rd" },
      { id: "D01", name: "Norwood-205 St" },
      { id: "R34", name: "Prospect Av" },
      { id: "D07", name: "Tremont Av" },
      { id: "R32", name: "Union St" },
      { id: "D20", name: "W 4 St-Wash Sq" },
    ],
    "E": [
      { id: "A31", name: "14 St" },
      { id: "A30", name: "23 St" },
      { id: "A28", name: "34 St-Penn Station" },
      { id: "G20", name: "36 St" },
      { id: "A27", name: "42 St-Port Authority Bus Terminal" },
      { id: "G18", name: "46 St" },
      { id: "F12", name: "5 Av/53 St" },
      { id: "A25", name: "50 St" },
      { id: "G10", name: "63 Dr-Rego Park" },
      { id: "G15", name: "65 St" },
      { id: "G09", name: "67 Av" },
      { id: "D14", name: "7 Av" },
      { id: "F07", name: "75 Av" },
      { id: "F05", name: "Briarwood" },
      { id: "A34", name: "Canal St" },
      { id: "F09", name: "Court Sq-23 St" },
      { id: "G13", name: "Elmhurst Av" },
      { id: "G08", name: "Forest Hills-71 Av" },
      { id: "G12", name: "Grand Av-Newtown" },
      { id: "G14", name: "Jackson Hts-Roosevelt Av" },
      { id: "G05", name: "Jamaica Center-Parsons/Archer" },
      { id: "G07", name: "Jamaica-Van Wyck" },
      { id: "F06", name: "Kew Gardens-Union Tpke" },
      { id: "F11", name: "Lexington Av/53 St" },
      { id: "G16", name: "Northern Blvd" },
      { id: "G21", name: "Queens Plaza" },
      { id: "A33", name: "Spring St" },
      { id: "G19", name: "Steinway St" },
      { id: "G06", name: "Sutphin Blvd-Archer Av-JFK Airport" },
      { id: "A32", name: "W 4 St-Wash Sq" },
      { id: "G11", name: "Woodhaven Blvd" },
      { id: "E01", name: "World Trade Center" },
    ],
    "F": [
      { id: "D19", name: "14 St" },
      { id: "F25", name: "15 St-Prospect Park" },
      { id: "F02", name: "169 St" },
      { id: "F30", name: "18 Av" },
      { id: "F14", name: "2 Av" },
      { id: "B04", name: "21 St-Queensbridge" },
      { id: "D18", name: "23 St" },
      { id: "D17", name: "34 St-Herald Sq" },
      { id: "G20", name: "36 St" },
      { id: "F23", name: "4 Av-9 St" },
      { id: "D16", name: "42 St-Bryant Pk" },
      { id: "G18", name: "46 St" },
      { id: "D15", name: "47-50 Sts-Rockefeller Ctr" },
      { id: "B10", name: "57 St" },
      { id: "G10", name: "63 Dr-Rego Park" },
      { id: "G15", name: "65 St" },
      { id: "G09", name: "67 Av" },
      { id: "F24", name: "7 Av" },
      { id: "F07", name: "75 Av" },
      { id: "F31", name: "Avenue I" },
      { id: "F33", name: "Avenue N" },
      { id: "F34", name: "Avenue P" },
      { id: "F36", name: "Avenue U" },
      { id: "F38", name: "Avenue X" },
      { id: "F32", name: "Bay Pkwy" },
      { id: "F20", name: "Bergen St" },
      { id: "F05", name: "Briarwood" },
      { id: "D21", name: "Broadway-Lafayette St" },
      { id: "F21", name: "Carroll St" },
      { id: "F27", name: "Church Av" },
      { id: "D43", name: "Coney Island-Stillwell Av" },
      { id: "F15", name: "Delancey St-Essex St" },
      { id: "F29", name: "Ditmas Av" },
      { id: "F16", name: "East Broadway" },
      { id: "G13", name: "Elmhurst Av" },
      { id: "G08", name: "Forest Hills-71 Av" },
      { id: "F26", name: "Fort Hamilton Pkwy" },
      { id: "G12", name: "Grand Av-Newtown" },
      { id: "G14", name: "Jackson Hts-Roosevelt Av" },
      { id: "F01", name: "Jamaica-179 St" },
      { id: "A41", name: "Jay St-MetroTech" },
      { id: "F06", name: "Kew Gardens-Union Tpke" },
      { id: "F35", name: "Kings Hwy" },
      { id: "B08", name: "Lexington Av/63 St" },
      { id: "F39", name: "Neptune Av" },
      { id: "G16", name: "Northern Blvd" },
      { id: "F03", name: "Parsons Blvd" },
      { id: "B06", name: "Roosevelt Island" },
      { id: "F22", name: "Smith-9 Sts" },
      { id: "G19", name: "Steinway St" },
      { id: "F04", name: "Sutphin Blvd" },
      { id: "D20", name: "W 4 St-Wash Sq" },
      { id: "D42", name: "W 8 St-NY Aquarium" },
      { id: "G11", name: "Woodhaven Blvd" },
      { id: "F18", name: "York St" },
    ],
    "G": [
      { id: "F25", name: "15 St-Prospect Park" },
      { id: "G24", name: "21 St" },
      { id: "F23", name: "4 Av-9 St" },
      { id: "F24", name: "7 Av" },
      { id: "G33", name: "Bedford-Nostrand Avs" },
      { id: "F20", name: "Bergen St" },
      { id: "G30", name: "Broadway" },
      { id: "F21", name: "Carroll St" },
      { id: "F27", name: "Church Av" },
      { id: "G34", name: "Classon Av" },
      { id: "G35", name: "Clinton-Washington Avs" },
      { id: "G22", name: "Court Sq" },
      { id: "G31", name: "Flushing Av" },
      { id: "F26", name: "Fort Hamilton Pkwy" },
      { id: "G36", name: "Fulton St" },
      { id: "G26", name: "Greenpoint Av" },
      { id: "A42", name: "Hoyt-Schermerhorn Sts" },
      { id: "G29", name: "Metropolitan Av" },
      { id: "G32", name: "Myrtle-Willoughby Avs" },
      { id: "G28", name: "Nassau Av" },
      { id: "F22", name: "Smith-9 Sts" },
    ],
    "J": [
      { id: "J14", name: "104 St" },
      { id: "J13", name: "111 St" },
      { id: "J12", name: "121 St" },
      { id: "J17", name: "75 St-Elderts Ln" },
      { id: "J16", name: "85 St-Forest Pkwy" },
      { id: "J24", name: "Alabama Av" },
      { id: "M19", name: "Bowery" },
      { id: "M23", name: "Broad St" },
      { id: "J27", name: "Broadway Junction" },
      { id: "M20", name: "Canal St" },
      { id: "M21", name: "Chambers St" },
      { id: "J28", name: "Chauncey St" },
      { id: "J22", name: "Cleveland St" },
      { id: "J20", name: "Crescent St" },
      { id: "J19", name: "Cypress Hills" },
      { id: "M18", name: "Delancey St-Essex St" },
      { id: "M12", name: "Flushing Av" },
      { id: "M22", name: "Fulton St" },
      { id: "J30", name: "Gates Av" },
      { id: "J29", name: "Halsey St" },
      { id: "M14", name: "Hewes St" },
      { id: "G05", name: "Jamaica Center-Parsons/Archer" },
      { id: "J31", name: "Kosciuszko St" },
      { id: "M13", name: "Lorimer St" },
      { id: "M16", name: "Marcy Av" },
      { id: "M11", name: "Myrtle Av" },
      { id: "J21", name: "Norwood Av" },
      { id: "G06", name: "Sutphin Blvd-Archer Av-JFK Airport" },
      { id: "J23", name: "Van Siclen Av" },
      { id: "J15", name: "Woodhaven Blvd" },
    ],
    "L": [
      { id: "L06", name: "1 Av" },
      { id: "L03", name: "14 St-Union Sq" },
      { id: "L05", name: "3 Av" },
      { id: "L02", name: "6 Av" },
      { id: "L01", name: "8 Av" },
      { id: "L24", name: "Atlantic Av" },
      { id: "L08", name: "Bedford Av" },
      { id: "L22", name: "Broadway Junction" },
      { id: "L21", name: "Bushwick Av-Aberdeen St" },
      { id: "L29", name: "Canarsie-Rockaway Pkwy" },
      { id: "L16", name: "DeKalb Av" },
      { id: "L28", name: "East 105 St" },
      { id: "L11", name: "Graham Av" },
      { id: "L12", name: "Grand St" },
      { id: "L19", name: "Halsey St" },
      { id: "L15", name: "Jefferson St" },
      { id: "L26", name: "Livonia Av" },
      { id: "L10", name: "Lorimer St" },
      { id: "L13", name: "Montrose Av" },
      { id: "L14", name: "Morgan Av" },
      { id: "L17", name: "Myrtle-Wyckoff Avs" },
      { id: "L27", name: "New Lots Av" },
      { id: "L25", name: "Sutter Av" },
      { id: "L20", name: "Wilson Av" },
    ],
    "M": [
      { id: "D19", name: "14 St" },
      { id: "D18", name: "23 St" },
      { id: "D17", name: "34 St-Herald Sq" },
      { id: "G20", name: "36 St" },
      { id: "D16", name: "42 St-Bryant Pk" },
      { id: "G18", name: "46 St" },
      { id: "D15", name: "47-50 Sts-Rockefeller Ctr" },
      { id: "F12", name: "5 Av/53 St" },
      { id: "G10", name: "63 Dr-Rego Park" },
      { id: "G15", name: "65 St" },
      { id: "G09", name: "67 Av" },
      { id: "D21", name: "Broadway-Lafayette St" },
      { id: "M10", name: "Central Av" },
      { id: "F09", name: "Court Sq-23 St" },
      { id: "M18", name: "Delancey St-Essex St" },
      { id: "G13", name: "Elmhurst Av" },
      { id: "M12", name: "Flushing Av" },
      { id: "M05", name: "Forest Av" },
      { id: "G08", name: "Forest Hills-71 Av" },
      { id: "M04", name: "Fresh Pond Rd" },
      { id: "G12", name: "Grand Av-Newtown" },
      { id: "M14", name: "Hewes St" },
      { id: "G14", name: "Jackson Hts-Roosevelt Av" },
      { id: "M09", name: "Knickerbocker Av" },
      { id: "F11", name: "Lexington Av/53 St" },
      { id: "M13", name: "Lorimer St" },
      { id: "M16", name: "Marcy Av" },
      { id: "M01", name: "Middle Village-Metropolitan Av" },
      { id: "M11", name: "Myrtle Av" },
      { id: "M08", name: "Myrtle-Wyckoff Avs" },
      { id: "G16", name: "Northern Blvd" },
      { id: "G21", name: "Queens Plaza" },
      { id: "M06", name: "Seneca Av" },
      { id: "G19", name: "Steinway St" },
      { id: "D20", name: "W 4 St-Wash Sq" },
      { id: "G11", name: "Woodhaven Blvd" },
    ],
    "N": [
      { id: "R20", name: "14 St-Union Sq" },
      { id: "N05", name: "18 Av" },
      { id: "N06", name: "20 Av" },
      { id: "R19", name: "23 St" },
      { id: "R35", name: "25 St" },
      { id: "R18", name: "28 St" },
      { id: "R04", name: "30 Av" },
      { id: "R17", name: "34 St-Herald Sq" },
      { id: "R06", name: "36 Av" },
      { id: "R36", name: "36 St" },
      { id: "R08", name: "39 Av-Dutch Kills" },
      { id: "R33", name: "4 Av-9 St" },
      { id: "R39", name: "45 St" },
      { id: "R15", name: "49 St" },
      { id: "R13", name: "5 Av/59 St" },
      { id: "R40", name: "53 St" },
      { id: "R14", name: "57 St-7 Av" },
      { id: "R41", name: "59 St" },
      { id: "Q03", name: "72 St" },
      { id: "N02", name: "8 Av" },
      { id: "R21", name: "8 St-NYU" },
      { id: "N10", name: "86 St" },
      { id: "Q04", name: "86 St" },
      { id: "Q05", name: "96 St" },
      { id: "R03", name: "Astoria Blvd" },
      { id: "R01", name: "Astoria-Ditmars Blvd" },
      { id: "R31", name: "Atlantic Av-Barclays Ctr" },
      { id: "N09", name: "Avenue U" },
      { id: "N07", name: "Bay Pkwy" },
      { id: "R05", name: "Broadway" },
      { id: "Q01", name: "Canal St" },
      { id: "R23", name: "Canal St" },
      { id: "R24", name: "City Hall" },
      { id: "D43", name: "Coney Island-Stillwell Av" },
      { id: "R25", name: "Cortlandt St" },
      { id: "R28", name: "Court St" },
      { id: "R30", name: "DeKalb Av" },
      { id: "N03", name: "Fort Hamilton Pkwy" },
      { id: "R29", name: "Jay St-MetroTech" },
      { id: "N08", name: "Kings Hwy" },
      { id: "R11", name: "Lexington Av/59 St" },
      { id: "B08", name: "Lexington Av/63 St" },
      { id: "N04", name: "New Utrecht Av" },
      { id: "R22", name: "Prince St" },
      { id: "R34", name: "Prospect Av" },
      { id: "R09", name: "Queensboro Plaza" },
      { id: "R26", name: "Rector St" },
      { id: "R16", name: "Times Sq-42 St" },
      { id: "R32", name: "Union St" },
      { id: "R27", name: "Whitehall St-South Ferry" },
    ],
    "Q": [
      { id: "R20", name: "14 St-Union Sq" },
      { id: "R19", name: "23 St" },
      { id: "R18", name: "28 St" },
      { id: "R17", name: "34 St-Herald Sq" },
      { id: "R15", name: "49 St" },
      { id: "R14", name: "57 St-7 Av" },
      { id: "D25", name: "7 Av" },
      { id: "Q03", name: "72 St" },
      { id: "R21", name: "8 St-NYU" },
      { id: "Q04", name: "86 St" },
      { id: "Q05", name: "96 St" },
      { id: "D24", name: "Atlantic Av-Barclays Ctr" },
      { id: "D32", name: "Avenue H" },
      { id: "D33", name: "Avenue J" },
      { id: "D34", name: "Avenue M" },
      { id: "D37", name: "Avenue U" },
      { id: "D29", name: "Beverley Rd" },
      { id: "D40", name: "Brighton Beach" },
      { id: "Q01", name: "Canal St" },
      { id: "D28", name: "Church Av" },
      { id: "D43", name: "Coney Island-Stillwell Av" },
      { id: "D30", name: "Cortelyou Rd" },
      { id: "R30", name: "DeKalb Av" },
      { id: "D35", name: "Kings Hwy" },
      { id: "B08", name: "Lexington Av/63 St" },
      { id: "D38", name: "Neck Rd" },
      { id: "D31", name: "Newkirk Plaza" },
      { id: "D41", name: "Ocean Pkwy" },
      { id: "D27", name: "Parkside Av" },
      { id: "R22", name: "Prince St" },
      { id: "D26", name: "Prospect Park" },
      { id: "D39", name: "Sheepshead Bay" },
      { id: "R16", name: "Times Sq-42 St" },
      { id: "D42", name: "W 8 St-NY Aquarium" },
    ],
    "R": [
      { id: "R20", name: "14 St-Union Sq" },
      { id: "R19", name: "23 St" },
      { id: "R35", name: "25 St" },
      { id: "R18", name: "28 St" },
      { id: "R17", name: "34 St-Herald Sq" },
      { id: "R36", name: "36 St" },
      { id: "G20", name: "36 St" },
      { id: "R33", name: "4 Av-9 St" },
      { id: "R39", name: "45 St" },
      { id: "G18", name: "46 St" },
      { id: "R15", name: "49 St" },
      { id: "R13", name: "5 Av/59 St" },
      { id: "R40", name: "53 St" },
      { id: "R14", name: "57 St-7 Av" },
      { id: "R41", name: "59 St" },
      { id: "G10", name: "63 Dr-Rego Park" },
      { id: "G15", name: "65 St" },
      { id: "G09", name: "67 Av" },
      { id: "Q03", name: "72 St" },
      { id: "R43", name: "77 St" },
      { id: "R21", name: "8 St-NYU" },
      { id: "R44", name: "86 St" },
      { id: "Q04", name: "86 St" },
      { id: "Q05", name: "96 St" },
      { id: "R31", name: "Atlantic Av-Barclays Ctr" },
      { id: "R42", name: "Bay Ridge Av" },
      { id: "R45", name: "Bay Ridge-95 St" },
      { id: "R23", name: "Canal St" },
      { id: "R24", name: "City Hall" },
      { id: "R25", name: "Cortlandt St" },
      { id: "R28", name: "Court St" },
      { id: "R30", name: "DeKalb Av" },
      { id: "G13", name: "Elmhurst Av" },
      { id: "G08", name: "Forest Hills-71 Av" },
      { id: "G12", name: "Grand Av-Newtown" },
      { id: "G14", name: "Jackson Hts-Roosevelt Av" },
      { id: "R29", name: "Jay St-MetroTech" },
      { id: "R11", name: "Lexington Av/59 St" },
      { id: "B08", name: "Lexington Av/63 St" },
      { id: "G16", name: "Northern Blvd" },
      { id: "R22", name: "Prince St" },
      { id: "R34", name: "Prospect Av" },
      { id: "G21", name: "Queens Plaza" },
      { id: "R26", name: "Rector St" },
      { id: "G19", name: "Steinway St" },
      { id: "R16", name: "Times Sq-42 St" },
      { id: "R32", name: "Union St" },
      { id: "R27", name: "Whitehall St-South Ferry" },
      { id: "G11", name: "Woodhaven Blvd" },
    ],
    "S": [
      { id: "H14", name: "Beach 105 St" },
      { id: "H12", name: "Beach 90 St" },
      { id: "H13", name: "Beach 98 St" },
      { id: "S04", name: "Botanic Garden" },
      { id: "H04", name: "Broad Channel" },
      { id: "S01", name: "Franklin Av" },
      { id: "901", name: "Grand Central-42 St" },
      { id: "S03", name: "Park Pl" },
      { id: "D26", name: "Prospect Park" },
      { id: "H15", name: "Rockaway Park-Beach 116 St" },
      { id: "902", name: "Times Sq-42 St" },
    ],
    "SIR": [
      { id: "S17", name: "Annadale" },
      { id: "S11", name: "Arthur Kill" },
      { id: "S20", name: "Bay Terrace" },
      { id: "S28", name: "Clifton" },
      { id: "S25", name: "Dongan Hills" },
      { id: "S18", name: "Eltingville" },
      { id: "S23", name: "Grant City" },
      { id: "S27", name: "Grasmere" },
      { id: "S19", name: "Great Kills" },
      { id: "S16", name: "Huguenot" },
      { id: "S24", name: "Jefferson Av" },
      { id: "S22", name: "New Dorp" },
      { id: "S21", name: "Oakwood Heights" },
      { id: "S26", name: "Old Town" },
      { id: "S14", name: "Pleasant Plains" },
      { id: "S15", name: "Prince's Bay" },
      { id: "S13", name: "Richmond Valley" },
      { id: "S31", name: "St George" },
      { id: "S29", name: "Stapleton" },
      { id: "S30", name: "Tompkinsville" },
      { id: "S09", name: "Tottenville" },
    ],
    "W": [
      { id: "R20", name: "14 St-Union Sq" },
      { id: "N05", name: "18 Av" },
      { id: "N06", name: "20 Av" },
      { id: "R19", name: "23 St" },
      { id: "R35", name: "25 St" },
      { id: "R18", name: "28 St" },
      { id: "R04", name: "30 Av" },
      { id: "R17", name: "34 St-Herald Sq" },
      { id: "R06", name: "36 Av" },
      { id: "R36", name: "36 St" },
      { id: "R08", name: "39 Av-Dutch Kills" },
      { id: "R33", name: "4 Av-9 St" },
      { id: "R39", name: "45 St" },
      { id: "R15", name: "49 St" },
      { id: "R13", name: "5 Av/59 St" },
      { id: "R40", name: "53 St" },
      { id: "R14", name: "57 St-7 Av" },
      { id: "R41", name: "59 St" },
      { id: "N02", name: "8 Av" },
      { id: "R21", name: "8 St-NYU" },
      { id: "N10", name: "86 St" },
      { id: "R03", name: "Astoria Blvd" },
      { id: "R01", name: "Astoria-Ditmars Blvd" },
      { id: "R31", name: "Atlantic Av-Barclays Ctr" },
      { id: "N09", name: "Avenue U" },
      { id: "N07", name: "Bay Pkwy" },
      { id: "R05", name: "Broadway" },
      { id: "R23", name: "Canal St" },
      { id: "R24", name: "City Hall" },
      { id: "R25", name: "Cortlandt St" },
      { id: "R28", name: "Court St" },
      { id: "R30", name: "DeKalb Av" },
      { id: "N03", name: "Fort Hamilton Pkwy" },
      { id: "R29", name: "Jay St-MetroTech" },
      { id: "N08", name: "Kings Hwy" },
      { id: "R11", name: "Lexington Av/59 St" },
      { id: "N04", name: "New Utrecht Av" },
      { id: "R22", name: "Prince St" },
      { id: "R34", name: "Prospect Av" },
      { id: "R09", name: "Queensboro Plaza" },
      { id: "R26", name: "Rector St" },
      { id: "R16", name: "Times Sq-42 St" },
      { id: "R32", name: "Union St" },
      { id: "R27", name: "Whitehall St-South Ferry" },
    ],
    "Z": [
      { id: "J14", name: "104 St" },
      { id: "J12", name: "121 St" },
      { id: "J17", name: "75 St-Elderts Ln" },
      { id: "J24", name: "Alabama Av" },
      { id: "M19", name: "Bowery" },
      { id: "M23", name: "Broad St" },
      { id: "J27", name: "Broadway Junction" },
      { id: "M20", name: "Canal St" },
      { id: "M21", name: "Chambers St" },
      { id: "J28", name: "Chauncey St" },
      { id: "J20", name: "Crescent St" },
      { id: "M18", name: "Delancey St-Essex St" },
      { id: "M22", name: "Fulton St" },
      { id: "J30", name: "Gates Av" },
      { id: "G05", name: "Jamaica Center-Parsons/Archer" },
      { id: "M16", name: "Marcy Av" },
      { id: "M11", name: "Myrtle Av" },
      { id: "J21", name: "Norwood Av" },
      { id: "G06", name: "Sutphin Blvd-Archer Av-JFK Airport" },
      { id: "J23", name: "Van Siclen Av" },
      { id: "J15", name: "Woodhaven Blvd" },
    ],
  };

export const LINES_BY_STATION = {
  "101": ["1"],
  "103": ["1"],
  "104": ["1"],
  "106": ["1"],
  "107": ["1"],
  "108": ["1"],
  "109": ["1"],
  "110": ["1"],
  "111": ["1"],
  "112": ["1"],
  "113": ["1"],
  "114": ["1"],
  "115": ["1"],
  "116": ["1"],
  "117": ["1"],
  "118": ["1"],
  "119": ["1"],
  "120": ["1", "2", "3"],
  "121": ["1", "2"],
  "122": ["1", "2"],
  "123": ["1", "2", "3"],
  "124": ["1", "2"],
  "125": ["1", "2"],
  "126": ["1", "2"],
  "127": ["1", "2", "3"],
  "128": ["1", "2", "3"],
  "129": ["1", "2"],
  "130": ["1", "2"],
  "131": ["1", "2"],
  "132": ["1", "2", "3"],
  "133": ["1", "2"],
  "134": ["1", "2"],
  "135": ["1", "2"],
  "136": ["1", "2"],
  "137": ["1", "2", "3"],
  "138": ["1"],
  "139": ["1"],
  "142": ["1"],
  "201": ["2"],
  "204": ["2", "5"],
  "205": ["2", "5"],
  "206": ["2", "5"],
  "207": ["2", "5"],
  "208": ["2", "5"],
  "209": ["2", "5"],
  "210": ["2", "5"],
  "211": ["2", "5"],
  "212": ["2", "5"],
  "213": ["2", "5"],
  "214": ["2", "5"],
  "215": ["2", "5"],
  "216": ["2", "5"],
  "217": ["2", "5"],
  "218": ["2", "5"],
  "219": ["2", "5"],
  "220": ["2", "5"],
  "221": ["2", "5"],
  "222": ["2", "5"],
  "224": ["2", "3"],
  "225": ["2", "3"],
  "226": ["2", "3"],
  "227": ["2", "3"],
  "228": ["2", "3"],
  "229": ["2", "3"],
  "230": ["2", "3"],
  "231": ["2", "3"],
  "232": ["2", "3"],
  "233": ["2", "3"],
  "234": ["2", "3", "4", "5"],
  "235": ["2", "3", "4", "5"],
  "236": ["2", "3", "4"],
  "237": ["2", "3", "4"],
  "238": ["2", "3", "4"],
  "239": ["2", "3", "4", "5"],
  "241": ["2", "5"],
  "242": ["2", "5"],
  "243": ["2", "5"],
  "244": ["2", "5"],
  "245": ["2", "5"],
  "246": ["2", "5"],
  "247": ["2", "5"],
  "248": ["2", "3", "4", "5"],
  "249": ["2", "3", "4", "5"],
  "250": ["2", "3", "4", "5"],
  "251": ["2", "3", "4", "5"],
  "252": ["2", "3", "4", "5"],
  "253": ["2", "3", "4", "5"],
  "254": ["2", "3", "4", "5"],
  "255": ["2", "3", "4", "5"],
  "256": ["2", "3", "4", "5"],
  "257": ["2", "3", "4", "5"],
  "301": ["3"],
  "302": ["3"],
  "401": ["4"],
  "402": ["4"],
  "405": ["4"],
  "406": ["4"],
  "407": ["4"],
  "408": ["4"],
  "409": ["4"],
  "410": ["4"],
  "411": ["4"],
  "412": ["4"],
  "413": ["4"],
  "414": ["4"],
  "415": ["4"],
  "416": ["4", "5"],
  "418": ["4", "5"],
  "419": ["4", "5"],
  "420": ["4", "5"],
  "423": ["4", "5"],
  "501": ["5"],
  "502": ["5"],
  "503": ["5"],
  "504": ["5"],
  "505": ["5"],
  "601": ["6", "6X"],
  "602": ["6", "6X"],
  "603": ["6", "6X"],
  "604": ["6", "6X"],
  "606": ["6", "6X"],
  "607": ["6", "6X"],
  "608": ["6", "6X"],
  "609": ["6"],
  "610": ["6"],
  "611": ["6"],
  "612": ["6"],
  "613": ["6", "6X"],
  "614": ["6"],
  "615": ["6"],
  "616": ["6"],
  "617": ["6"],
  "618": ["6"],
  "619": ["6", "6X"],
  "621": ["4", "5", "6", "6X"],
  "622": ["4", "6", "6X"],
  "623": ["4", "6", "6X"],
  "624": ["4", "6", "6X"],
  "625": ["4", "6", "6X"],
  "626": ["4", "5", "6", "6X"],
  "627": ["4", "6", "6X"],
  "628": ["4", "6", "6X"],
  "629": ["4", "5", "6", "6X"],
  "630": ["4", "6", "6X"],
  "631": ["4", "5", "6", "6X"],
  "632": ["4", "6", "6X"],
  "633": ["4", "6", "6X"],
  "634": ["4", "6", "6X"],
  "635": ["4", "5", "6", "6X"],
  "636": ["4", "6", "6X"],
  "637": ["4", "6", "6X"],
  "638": ["4", "6", "6X"],
  "639": ["4", "6", "6X"],
  "640": ["4", "5", "6", "6X"],
  "701": ["7", "7X"],
  "702": ["7", "7X"],
  "705": ["7"],
  "706": ["7"],
  "707": ["7", "7X"],
  "708": ["7"],
  "709": ["7"],
  "710": ["7", "7X"],
  "711": ["7", "7X"],
  "712": ["7", "7X"],
  "713": ["7", "7X"],
  "714": ["7", "7X"],
  "715": ["7", "7X"],
  "716": ["7", "7X"],
  "718": ["7", "7X"],
  "719": ["7", "7X"],
  "720": ["7", "7X"],
  "721": ["7", "7X"],
  "723": ["7", "7X"],
  "724": ["7", "7X"],
  "725": ["7", "7X"],
  "726": ["7", "7X"],
  "901": ["S"],
  "902": ["S"],
  "A02": ["A"],
  "A03": ["A"],
  "A05": ["A"],
  "A06": ["A"],
  "A07": ["A"],
  "A09": ["A", "C"],
  "A10": ["A", "C"],
  "A11": ["A", "C"],
  "A12": ["A", "C"],
  "A14": ["A", "B", "C"],
  "A15": ["A", "B", "C", "D"],
  "A16": ["A", "B", "C"],
  "A17": ["A", "B", "C"],
  "A18": ["A", "B", "C"],
  "A19": ["A", "B", "C"],
  "A20": ["A", "B", "C"],
  "A21": ["A", "B", "C"],
  "A22": ["A", "B", "C"],
  "A24": ["A", "B", "C", "D"],
  "A25": ["A", "C", "E"],
  "A27": ["A", "C", "E"],
  "A28": ["A", "C", "E"],
  "A30": ["A", "C", "E"],
  "A31": ["A", "C", "E"],
  "A32": ["A", "C", "E"],
  "A33": ["A", "C", "E"],
  "A34": ["A", "C", "E"],
  "A36": ["A", "C"],
  "A38": ["A", "C"],
  "A40": ["A", "C"],
  "A41": ["A", "C", "F"],
  "A42": ["A", "C", "G"],
  "A43": ["A", "C"],
  "A44": ["A", "C"],
  "A45": ["A", "C"],
  "A46": ["A", "C"],
  "A47": ["A", "C"],
  "A48": ["A", "C"],
  "A49": ["A", "C"],
  "A50": ["A", "C"],
  "A51": ["A", "C"],
  "A52": ["A", "C"],
  "A53": ["A", "C"],
  "A54": ["A", "C"],
  "A55": ["A", "C"],
  "A57": ["A"],
  "A59": ["A"],
  "A60": ["A"],
  "A61": ["A"],
  "A63": ["A"],
  "A64": ["A"],
  "A65": ["A"],
  "B04": ["F"],
  "B06": ["F"],
  "B08": ["F", "N", "Q", "R"],
  "B10": ["F"],
  "B12": ["D"],
  "B13": ["D"],
  "B14": ["D"],
  "B15": ["D"],
  "B16": ["D"],
  "B17": ["D"],
  "B18": ["D"],
  "B19": ["D"],
  "B20": ["D"],
  "B21": ["D"],
  "B22": ["D"],
  "B23": ["D"],
  "D01": ["D"],
  "D03": ["B", "D"],
  "D04": ["B", "D"],
  "D05": ["B", "D"],
  "D06": ["B", "D"],
  "D07": ["B", "D"],
  "D08": ["B", "D"],
  "D09": ["B", "D"],
  "D10": ["B", "D"],
  "D11": ["B", "D"],
  "D12": ["B", "D"],
  "D13": ["B", "D"],
  "D14": ["B", "D", "E"],
  "D15": ["B", "D", "F", "M"],
  "D16": ["B", "D", "F", "M"],
  "D17": ["B", "D", "F", "M"],
  "D18": ["F", "M"],
  "D19": ["F", "M"],
  "D20": ["B", "D", "F", "M"],
  "D21": ["B", "D", "F", "M"],
  "D22": ["B", "D"],
  "D24": ["B", "Q"],
  "D25": ["B", "Q"],
  "D26": ["B", "Q", "S"],
  "D27": ["Q"],
  "D28": ["B", "Q"],
  "D29": ["Q"],
  "D30": ["Q"],
  "D31": ["B", "Q"],
  "D32": ["Q"],
  "D33": ["Q"],
  "D34": ["Q"],
  "D35": ["B", "Q"],
  "D37": ["Q"],
  "D38": ["Q"],
  "D39": ["B", "Q"],
  "D40": ["B", "Q"],
  "D41": ["Q"],
  "D42": ["F", "Q"],
  "D43": ["D", "F", "N", "Q"],
  "E01": ["E"],
  "F01": ["F"],
  "F02": ["F"],
  "F03": ["F"],
  "F04": ["F"],
  "F05": ["E", "F"],
  "F06": ["E", "F"],
  "F07": ["E", "F"],
  "F09": ["E", "M"],
  "F11": ["E", "M"],
  "F12": ["E", "M"],
  "F14": ["F"],
  "F15": ["F"],
  "F16": ["F"],
  "F18": ["F"],
  "F20": ["F", "G"],
  "F21": ["F", "G"],
  "F22": ["F", "G"],
  "F23": ["F", "G"],
  "F24": ["F", "G"],
  "F25": ["F", "G"],
  "F26": ["F", "G"],
  "F27": ["F", "G"],
  "F29": ["F"],
  "F30": ["F"],
  "F31": ["F"],
  "F32": ["F"],
  "F33": ["F"],
  "F34": ["F"],
  "F35": ["F"],
  "F36": ["F"],
  "F38": ["F"],
  "F39": ["F"],
  "G05": ["E", "J", "Z"],
  "G06": ["E", "J", "Z"],
  "G07": ["E"],
  "G08": ["E", "F", "M", "R"],
  "G09": ["E", "F", "M", "R"],
  "G10": ["E", "F", "M", "R"],
  "G11": ["E", "F", "M", "R"],
  "G12": ["E", "F", "M", "R"],
  "G13": ["E", "F", "M", "R"],
  "G14": ["E", "F", "M", "R"],
  "G15": ["E", "F", "M", "R"],
  "G16": ["E", "F", "M", "R"],
  "G18": ["E", "F", "M", "R"],
  "G19": ["E", "F", "M", "R"],
  "G20": ["E", "F", "M", "R"],
  "G21": ["E", "M", "R"],
  "G22": ["G"],
  "G24": ["G"],
  "G26": ["G"],
  "G28": ["G"],
  "G29": ["G"],
  "G30": ["G"],
  "G31": ["G"],
  "G32": ["G"],
  "G33": ["G"],
  "G34": ["G"],
  "G35": ["G"],
  "G36": ["G"],
  "H01": ["A"],
  "H02": ["A"],
  "H03": ["A"],
  "H04": ["A", "S"],
  "H06": ["A"],
  "H07": ["A"],
  "H08": ["A"],
  "H09": ["A"],
  "H10": ["A"],
  "H11": ["A"],
  "H12": ["A", "S"],
  "H13": ["A", "S"],
  "H14": ["A", "S"],
  "H15": ["A", "S"],
  "J12": ["J", "Z"],
  "J13": ["J"],
  "J14": ["J", "Z"],
  "J15": ["J", "Z"],
  "J16": ["J"],
  "J17": ["J", "Z"],
  "J19": ["J"],
  "J20": ["J", "Z"],
  "J21": ["J", "Z"],
  "J22": ["J"],
  "J23": ["J", "Z"],
  "J24": ["J", "Z"],
  "J27": ["J", "Z"],
  "J28": ["J", "Z"],
  "J29": ["J"],
  "J30": ["J", "Z"],
  "J31": ["J"],
  "L01": ["L"],
  "L02": ["L"],
  "L03": ["L"],
  "L05": ["L"],
  "L06": ["L"],
  "L08": ["L"],
  "L10": ["L"],
  "L11": ["L"],
  "L12": ["L"],
  "L13": ["L"],
  "L14": ["L"],
  "L15": ["L"],
  "L16": ["L"],
  "L17": ["L"],
  "L19": ["L"],
  "L20": ["L"],
  "L21": ["L"],
  "L22": ["L"],
  "L24": ["L"],
  "L25": ["L"],
  "L26": ["L"],
  "L27": ["L"],
  "L28": ["L"],
  "L29": ["L"],
  "M01": ["M"],
  "M04": ["M"],
  "M05": ["M"],
  "M06": ["M"],
  "M08": ["M"],
  "M09": ["M"],
  "M10": ["M"],
  "M11": ["J", "M", "Z"],
  "M12": ["J", "M"],
  "M13": ["J", "M"],
  "M14": ["J", "M"],
  "M16": ["J", "M", "Z"],
  "M18": ["J", "M", "Z"],
  "M19": ["J", "Z"],
  "M20": ["J", "Z"],
  "M21": ["J", "Z"],
  "M22": ["J", "Z"],
  "M23": ["J", "Z"],
  "N02": ["N", "W"],
  "N03": ["N", "W"],
  "N04": ["N", "W"],
  "N05": ["N", "W"],
  "N06": ["N", "W"],
  "N07": ["N", "W"],
  "N08": ["N", "W"],
  "N09": ["N", "W"],
  "N10": ["N", "W"],
  "Q01": ["N", "Q"],
  "Q03": ["N", "Q", "R"],
  "Q04": ["N", "Q", "R"],
  "Q05": ["N", "Q", "R"],
  "R01": ["N", "W"],
  "R03": ["N", "W"],
  "R04": ["N", "W"],
  "R05": ["N", "W"],
  "R06": ["N", "W"],
  "R08": ["N", "W"],
  "R09": ["N", "W"],
  "R11": ["N", "R", "W"],
  "R13": ["N", "R", "W"],
  "R14": ["N", "Q", "R", "W"],
  "R15": ["N", "Q", "R", "W"],
  "R16": ["N", "Q", "R", "W"],
  "R17": ["N", "Q", "R", "W"],
  "R18": ["N", "Q", "R", "W"],
  "R19": ["N", "Q", "R", "W"],
  "R20": ["N", "Q", "R", "W"],
  "R21": ["N", "Q", "R", "W"],
  "R22": ["N", "Q", "R", "W"],
  "R23": ["N", "R", "W"],
  "R24": ["N", "R", "W"],
  "R25": ["N", "R", "W"],
  "R26": ["N", "R", "W"],
  "R27": ["N", "R", "W"],
  "R28": ["N", "R", "W"],
  "R29": ["N", "R", "W"],
  "R30": ["B", "D", "N", "Q", "R", "W"],
  "R31": ["D", "N", "R", "W"],
  "R32": ["D", "N", "R", "W"],
  "R33": ["D", "N", "R", "W"],
  "R34": ["D", "N", "R", "W"],
  "R35": ["D", "N", "R", "W"],
  "R36": ["D", "N", "R", "W"],
  "R39": ["N", "R", "W"],
  "R40": ["N", "R", "W"],
  "R41": ["N", "R", "W"],
  "R42": ["R"],
  "R43": ["R"],
  "R44": ["R"],
  "R45": ["R"],
  "S01": ["S"],
  "S03": ["S"],
  "S04": ["S"],
  "S09": ["SIR"],
  "S11": ["SIR"],
  "S13": ["SIR"],
  "S14": ["SIR"],
  "S15": ["SIR"],
  "S16": ["SIR"],
  "S17": ["SIR"],
  "S18": ["SIR"],
  "S19": ["SIR"],
  "S20": ["SIR"],
  "S21": ["SIR"],
  "S22": ["SIR"],
  "S23": ["SIR"],
  "S24": ["SIR"],
  "S25": ["SIR"],
  "S26": ["SIR"],
  "S27": ["SIR"],
  "S28": ["SIR"],
  "S29": ["SIR"],
  "S30": ["SIR"],
  "S31": ["SIR"],
};